-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 21:41:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gameDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gameDB` ;

-- -----------------------------------------------------
-- Schema gameDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gameDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `gameDB` ;

-- -----------------------------------------------------
-- Table `gameDB`.`Characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Characters` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Characters` (
  `idCharacters` INT NOT NULL AUTO_INCREMENT,
  `race` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `desctiption` VARCHAR(450) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `health` FLOAT NOT NULL,
  `speed` FLOAT NOT NULL,
  `p_attack` FLOAT NOT NULL,
  `m_attack` FLOAT NOT NULL,
  `range` FLOAT NOT NULL,
  `p_defence` FLOAT NOT NULL,
  `m_defence` FLOAT NOT NULL,
  `crit_possibility` FLOAT NOT NULL,
  `crit` FLOAT NOT NULL,
  `passive` VARCHAR(1000) NOT NULL,
  `special_1` VARCHAR(1000) NOT NULL,
  `special_2` VARCHAR(1000) NOT NULL,
  `special_3` VARCHAR(1000) NOT NULL,
  `rarity` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCharacters`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Cards` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Cards` (
  `idCards` INT NOT NULL AUTO_INCREMENT,
  `race` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `effect` VARCHAR(1000) NOT NULL,
  `condition` VARCHAR(1000) NOT NULL,
  `rarity` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCards`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`Characters_Shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Characters_Shop` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Characters_Shop` (
  `idCharacters_Shop` INT NOT NULL,
  `cost` INT NOT NULL,
  INDEX `FK_Characters_Shop_Id_idx` (`idCharacters_Shop` ASC) VISIBLE,
  CONSTRAINT `FK_Characters_Shop_Id`
    FOREIGN KEY (`idCharacters_Shop`)
    REFERENCES `gameDB`.`Characters` (`idCharacters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`Cards_Shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Cards_Shop` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Cards_Shop` (
  `idCards_Shop` INT NOT NULL,
  `cost` INT NOT NULL,
  INDEX `FK_Cards_Shop_Id_idx` (`idCards_Shop` ASC) VISIBLE,
  CONSTRAINT `FK_Cards_Shop_Id`
    FOREIGN KEY (`idCards_Shop`)
    REFERENCES `gameDB`.`Cards` (`idCards`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Players` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Players` (
  `idPlayers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `balance` INT NOT NULL,
  PRIMARY KEY (`idPlayers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`Owned_Characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Owned_Characters` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Owned_Characters` (
  `owned_character_id` INT NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `character_id` INT NOT NULL,
  PRIMARY KEY (`owned_character_id`, `playerId`),
  INDEX `player_id_idx` (`playerId` ASC) VISIBLE,
  INDEX `FK_Owned_Characters_Id_idx` (`character_id` ASC) VISIBLE,
  CONSTRAINT `FK_Player_Characters_Id`
    FOREIGN KEY (`playerId`)
    REFERENCES `gameDB`.`Players` (`idPlayers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Owned_Characters_Id`
    FOREIGN KEY (`character_id`)
    REFERENCES `gameDB`.`Characters` (`idCharacters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameDB`.`Owned_Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameDB`.`Owned_Cards` ;

CREATE TABLE IF NOT EXISTS `gameDB`.`Owned_Cards` (
  `owned_card_id` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  PRIMARY KEY (`owned_card_id`, `player_id`),
  INDEX `FK_Player_Cards_Id_idx` (`player_id` ASC) VISIBLE,
  INDEX `FK_Owned_Cards_Id_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `FK_Player_Cards_Id`
    FOREIGN KEY (`player_id`)
    REFERENCES `gameDB`.`Players` (`idPlayers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Owned_Cards_Id`
    FOREIGN KEY (`card_id`)
    REFERENCES `gameDB`.`Cards` (`idCards`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
